CONFIG_SPINNER_CURRSMP=y
CONFIG_SPINNER_FEEDBACK_MT6701=y
CONFIG_SPINNER_SVPWM=y
CONFIG_SPINNER_CLOOP=y

CONFIG_LOG=y
CONFIG_SHELL=y

CONFIG_SENSOR=y

CONFIG_DEBUG_OPTIMIZATIONS=y

CONFIG_BLDC=y
CONFIG_DRV83XX=y
CONFIG_FPU=y

CONFIG_MT6701_ENABLE_LAG=y
CONFIG_MT6701_LAG_VALUE=300

CONFIG_SPINNER_CLOOP_T_KP=2000
CONFIG_SPINNER_CLOOP_T_KI=0
CONFIG_SPINNER_CLOOP_F_KP=1500
CONFIG_SPINNER_CLOOP_F_KI=0