CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_STD_C23=y
CONFIG_SENSOR=y
CONFIG_MT6701=y
CONFIG_SPI_STM32_INTERRUPT=y

CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_PRINTK=y

CONFIG_SPINNER_CURRSMP=y
CONFIG_SPINNER_SVPWM=y
CONFIG_SPINNER_SVM=y
CONFIG_SPINNER_UTILS_STM32=y
CONFIG_CMSIS_DSP_COMPLEXMATH=y