# Copyright (c) 2025 Marcin Bober
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: app

  remotes:
    - name: mbober1
      url-base: https://github.com/mbober1
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: upstream
      repo-path: zephyr
      revision: v4.4.2
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - cmsis_6
          - hal_stm32
          - segger

    - name: mt6701
      remote: mbober1
      repo-path: MT6701-Zephyr-Module
      path: modules/lib/mt6701
      revision: master

    - name: drv83xx
      remote: mbober1
      repo-path: drv83xx-Zephyr-Module
      path: modules/lib/drv83xx
      revision: master

    - name: spinner
      remote: mbober1
      repo-path: spinner
      path: modules/lib/spinner
      revision: main
 